### ISSUE TITLE
Ticker call throws error

### ISSUE THREAD

**Issue by JsonSam** [kojnapp/bitstamp#16]
In ticker call I an getting the following error

undefined method `vwap=' for #Bitstamp::Ticker:0x000000099d85d8

My code:

@@bitstamp = @@config['bitstamp']
 Bitstamp.setup do | config |
    config.key = @@bitstamp[:api_key]
    config.secret = @@bitstamp[:api_secret]
    config.client_id = @@bitstamp[:client_id]
 end

get :ticker_info do
     Bitstamp.ticker
 end

**Comment by jenskanis** [comment]
@felipecsl that results in another error being thrown when running bundler. 

```
Could not find gem 'rest_client (>= 1.7.3)', which is required by gem 'bitstamp', in any of the
sources.
```

That's because the gem doesn't exist'. Maybe `rest-client` works?

**Comment by maran** [comment]
Could you try using the develop branch? I'm been trying to revive some of the dead parts of the code there. 

```
gem 'bitstamp', :github => 'kojnapp/bitstamp', branch: :develop
```

**Comment by jenskanis** [comment]
@maran that works fine. I think this issue can be closed, thanks for responding!
